# -*- coding: utf-8 -*-

from odoo import models, fields


class Attendance(models.Model):
    _name = 'attendance.attendance'
    _description = 'attendance'

    _rec_name = 'attendance'
    date = fields.Date(default=fields.Date.today, tracking=1)
    trainee = fields.Many2one()
    name = fields.Char() //autogenerated
    login_time = fields.Datetime(default=fields.Date.today, tracking=1)
    logout_time = fields.Datetime(default=fields.Date.today, tracking=1)
    hours = fields.Float()